### PR TITLE
feat: Add Project page and update Recruitment page, components

### PR DESCRIPTION
**Pull request by Alizaaaja4**
### What does this PR do?
- Updates the Navbar:
  - Changes the size of the navbar for better responsiveness.
  - Replaces the logo on the navbar for a refreshed look.
  - Changes the color of the 'LMS' button on the navbar for better visibility.
  
- Updates the Recruitment page:
  - Updates the content and layout of the Recruitment page.

- Project Page:
  - Adds new content for the Project page.

### Documentation:
- Documentation in the form of GIFs showing the updates to the pages and components.

### Checklist:
- Navbar updates (size, logo, 'LMS' button color)
- Recruitment page layout and content updates
- Project page content creation
- New assets in /public
Offcial Daskom Lab - Google Chrome 2024-12-06 14-55-53

### CODE REVIEW

**Comment by Zaidanfzn** [comment]
Overall, this looks good to me. The changes are well implemented and no further modifications are needed.

**Review by Zaidanfzn — COMMENTED** [review]
Overall, this looks good to me. The changes are well implemented and no further modifications are needed. However, I think it would be better to showcase the updates in a dynamic and sufficiently long format, preferably as a video, to make the review process clearer.

**Review by Zaidanfzn — APPROVED** [review]
Overall, this looks good to me. The changes are well implemented and no further modifications are needed. However, I think it would be better to showcase the updates in a dynamic and sufficiently long format, preferably as a video, to make the review process clearer.

**Comment by Alizaaaja4** [comment]
Thank you for the feedback, in the next PR I will attach it in video form.

**Pull request merged**
