### PR TITLE
feat: Add contentAbout Component and Improve Responsiveness

### PR DESCRIPTION
**Pull request by Zaidanfzn**
## Overview
This pull request introduces new features and improvements to enhance the website's functionality and responsiveness across devices.

## Video Overview

- [Desktop View Demonstration](https://github.com/user-attachments/assets/ee84382b-67a4-442f-8539-fe6fde84600d)

- [Mobile View Demonstration](https://github.com/user-attachments/assets/e25f5a35-d082-44be-b4ac-9df541f6e99e)

---

## Changes Made

1. **About Page**:
   - Developed a new contentAbout.tsx component to structure the About page.
   - Added gallery and location sections with a responsive design.

2. **Project Page**:
   - Integrated a background image for the header section in `contentProject.tsx`.

3. **Responsiveness**:
   - Implemented tablet and mobile friendly designs for all page and footer content.
   - Ensured layout components adapt seamlessly to smaller screens.

4. **Navbar**:
   - Designed a responsive hamburger menu for tablet and mobile views.
   - Ensured a consistent white color for the navbar across all pages.

## Notes
1. The navbar and footer are now fully responsive and optimized for all devices.
2. Applied hover effects and scaling enhancements to interactive elements.

---

### CODE REVIEW

**Review by Alizaaaja4 — CHANGES_REQUESTED** [review]
image

In my opinion, the margin distance between the description and the title is too wide. Maybe the distance could be reduced. As for the laptop mode, I think it's already very good

**Review by Alizaaaja4 — CHANGES_REQUESTED** [review]
Sorry, I'm late responding. If you have finished fixing it, please show the results so we can see.

**Comment by IritaSee** [comment]
ummm, stale (?). 
Any update for the new margin requested? @Zaidanfzn

**Comment by IritaSee** [comment]
From reading the recent push, it looks good for me.

**Comment by Zaidanfzn** [comment]
## I have implemented the requested improvements for the following :

1. **Adjusted the margin of the ProjectPage for better appearance on mobile devices.**
2. **Enhanced the layout of ContentAbout for tablet view.**
3. **Improved the design of ContentProject for tablet view.**
---

Below are the screenshots showing the updates :

**- ProjectPage (Mobile) :**
contentProject_Mobile


**- ContentAbout (Tablet) :**
contentAbout_Tablet


**- ContentProject (Tablet) :**
contentProject_Tablet

**Comment by Zaidanfzn** [comment]
## I have implemented the requested improvements for the following :

1. **Adjusted the margin of the ProjectPage for better appearance on mobile devices.**
2. **Enhanced the layout of ContentAbout for tablet view.**
3. **Improved the design of ContentProject for tablet view.**
---

Below are the screenshots showing the updates :

**- ProjectPage (Mobile) :**
contentProject_Mobile


**- ContentAbout (Tablet) :**
contentAbout_Tablet


**- ContentProject (Tablet) :**
contentProject_Tablet

**Review by Alizaaaja4 — APPROVED** [review]
Thank you for your contribution!
I have reviewed the changes made, and the results are excellent!

**Pull request merged**
