### PR TITLE
feat: make navbar fixed and add images for various sections

### PR DESCRIPTION
**Pull request by Alizaaaja4**
This PR includes several updates and feature additions to the website:

## Navbar
- Changed the navbar from `sticky` to `fixed`.

## Image Additions
Added images to various sections of the website to enhance visualization, including:
- **Carousel Event**: Displaying images related to different events.
- **Carousel Divisi**: Adding images representing each division.
- **Gallery**: Adding a new collection of photos.
- **Project Dlor**: Adding images with different themes.

link video:
https://drive.google.com/file/d/1GaSLcZ9_v_rklN5ndcSGXadCmWwny87R/view?usp=sharing

### CODE REVIEW

**Review by Zaidanfzn — CHANGES_REQUESTED** [review]
Everything looks good overall! However, for the `components/contentProject.tsx` pagination, there’s no clear demonstration of how the content changes when moving from the first page to the next. Wouldn't it be better to add a sample for the second page with slightly different content? This way, it would clearly show the content difference and how the transition works. What do you think?

**Comment by Alizaaaja4** [comment]
> Everything looks good overall! However, for the `components/contentProject.tsx` pagination, there’s no clear demonstration of how the content changes when moving from the first page to the next. Wouldn't it be better to add a sample for the second page with slightly different content? This way, it would clearly show the content difference and how the transition works. What do you think?

For the `components/contentProject.tsx` pagination, I did not provide visible content changes when switching pages because this process is better handled on the backend. In my opinion, it would be more efficient to test it directly alongside the backend implementation so that the data flow and content changes can be thoroughly tested without needing to add dummy content on the frontend.

**Review by Zaidanfzn — APPROVED** [review]
Okay I got it, everything looks good from my side!

**Comment by Alizaaaja4** [comment]
> > Everything looks good overall! However, for the `components/contentProject.tsx` pagination, there’s no clear demonstration of how the content changes when moving from the first page to the next. Wouldn't it be better to add a sample for the second page with slightly different content? This way, it would clearly show the content difference and how the transition works. What do you think?
> 
> For the `components/contentProject.tsx` pagination, I did not provide visible content changes when switching pages because this process is better handled on the backend. In my opinion, it would be more efficient to test it directly alongside the backend implementation so that the data flow and content changes can be thoroughly tested without needing to add dummy content on the frontend.

What do you think, @DiyArc-350 , as the backend developer?

**Pull request merged**
